### PR TITLE
Added StyleCop

### PR DESCRIPTION
**Pull request by AlexandreSanscartier**
StyleCop is a code checker that makes sure we conform to .NET and C# style conventions.

### CODE REVIEW

**Comment by keithiancolbourne** [comment]
Excited to see this in action, cool! Took a quick glance and have a comment. Would recommend not merging commented out code. Here's a good article from Kent C. Dodds (who if you don't know who he is -- he is THE JS guru) https://kentcdodds.com/blog/please-dont-commit-commented-out-code

**Comment by AlexandreSanscartier** [comment]
@keithiancolbourne As far as I can tell there isn't any commented code, but I might have missed it. If you can point it out in the code review that would be much appreciated. There is a lot of comments, but that's because vanilla StyleCop demands that you do. We can discuss as a group which rules to keep and which to ditch though. Thanks for the article though I agree commenting code is a nono.

**Comment by keithiancolbourne** [comment]
> @keithiancolbourne As far as I can tell there isn't any commented code, but I might have missed it. If you can point it out in the code review that would be much appreciated. There is a lot of comments, but that's because vanilla StyleCop demands that you do. We can discuss as a group which rules to keep and which to ditch though. Thanks for the article though I agree commenting code is a nono.

Ahh ok! I just saw the stuff like:

/// <summary>
    /// The applicant's main living address.
    /// </summary>

in a bunch of places, didn't look close enough to see that might have been StyleCop. Makes sense, thanks :)

**Comment by keithiancolbourne** [comment]
> > @keithiancolbourne As far as I can tell there isn't any commented code, but I might have missed it. If you can point it out in the code review that would be much appreciated. There is a lot of comments, but that's because vanilla StyleCop demands that you do. We can discuss as a group which rules to keep and which to ditch though. Thanks for the article though I agree commenting code is a nono.
> 
> Ahh ok! I just saw the stuff like:
> 
> ///
> 
> 
> /// The applicant's main living address.
> ///
> in a bunch of places, didn't look close enough to see that might have been StyleCop. Makes sense, thanks :)

and the markdown stripped out the summary commented summary tags...

**Review by tc-chris — APPROVED** [review]

**Pull request merged**
